### ISSUE TITLE
bug: fix variable precedence

### ISSUE THREAD

**Issue by reno-xjb** [ovh/venom#245]
As @nqb mentioned it in https://github.com/ovh/venom/issues/243#issuecomment-606684105, for now variables declared in a variable file loaded with `--var-from-file` take precedence over variables loaded with `--var`.

Usually, command line arguments have a higher priority than config files. Could it be fixed?

**Comment by nqb** [comment]
I'm not sure that the way to go.

From my point of view, `--var` and `--var-from-file` should have same precedence. They are both CLI arguments and should be considered identical. 

*But* we need to have a way to tell Venom reading variables from a place that have lower precedence in order to override any variables on command line.
