### ISSUE TITLE
Timeout declared two times in venom language

### ISSUE THREAD

**Issue by kevinramage** [ovh/venom#290]
Hello,

I work on a visual studio code extension for venom language and I see a strange point on venom language.
I see two attributes timeout, one native with executor (like delay and retry) and one dedicated to kafka executor.
The first one is declared as int, the second one declared as int64.

Do you think this two differents definition can impact the system ?
It's necessary to declare timeout attribute for Kafka system ?

Regards

**Comment by fsamin** [comment]
Technically, having two definitions is not really a problem, event if it is a bit weird.

But your right: it is useless to handle a specific timeout for context cancellation in the kafka executor because it already done in the layer above.
The funny thing is that the same timeout value is handled in venom in second and in millisecond in kafka

It is a bug and should be fixed
