### ISSUE TITLE
(suggestion) Customize test result filename

### ISSUE THREAD

**Issue by bcecchinato** [ovh/venom#757]
Hello !

Currently it is possible to cutomize the test report directory, but the filename is always `test_results_TEST-NAME.type`.
Is it possible to add an option to set a templatized name instead ?  This would allow us to add the timestamp in the filename, and some of the parameters, which will prevent our tests to override the repport each time it is launched.

Thanks !

**Comment by kpassoubady** [comment]
Yes, this is greatly help. When we run the test cases in parallel, unless you create an output directory for each test suite, the test results are overwritten due to the same test_results.html
Here is a sample directory structure. I

<img width="327" alt="image" src="https://github.com/ovh/venom/assets/1095193/c04556d5-05c7-498b-a77b-d844474aa388">

**Comment by kpassoubady** [comment]
Yes, adding a facility to customize the result file names is a good feature.

**Comment by yesnault** [comment]
if outputDir is set, It's expected to have the same filename each time venom is is triggered. If you want to save output files, you have to set another outputDir (or mv the outputDir) before running venom another time.

**Comment by kpassoubady** [comment]
But if you try to run them in parallel, it is a good feature to have a fileNameWithDDMMYY_HH24MMSS_SSS.ext

**Comment by yesnault** [comment]
run in parallel -> you have to use different output-dir
